Toolbar: Update the cite web menu entry
wikimedia-bg/wikipedia-ui pull request #14
Opened 2021-11-13 11:24 UTC by kerberizer

Ref: https://bg.wikipedia.org/w/index.php?oldid=11183934#{{%D0%A6%D0%B8%D1%82%D0%B0%D1%82_%D1%83%D0%B5%D0%B1}}

2021-11-13 12:00 UTC, bmanolov approved these changes

2021-11-14 10:12 UTC, petar-petrov-w requested changes

2021-11-14 10:12 UTC, petar-petrov-w commented on Common.js.d/Edit tools data.d/Цитат уеб
> +<nowiki>{{цитат уеб | уеб_адрес = >>|<< | заглавие = | дата = | достъп_дата = | фамилно_име = | първо_име = | автор_препратка = | издател = | архив_уеб_адрес = | архив_дата = | цитат = | език-скрит =
```suggestion
<nowiki>{{цитат уеб | уеб_адрес = >>|<<| заглавие = | дата = | достъп_дата = | фамилно_име = | първо_име = | автор_препратка = | издател = | архив_уеб_адрес = | архив_дата = | цитат = | език-скрит = | език = }}</nowiki>
```

2021-11-14 10:19 UTC, petar-petrov-w commented on Common.js.d/Edit tools data.d/Цитат уеб
> +<nowiki>{{цитат уеб | уеб_адрес = >>|<< | заглавие = | дата = | достъп_дата = | фамилно_име = | първо_име = | автор_препратка = | издател = | архив_уеб_адрес = | архив_дата = | цитат = | език-скрит =
Щом променяме форматирането тук, то нека го направим и за другите шаблони [Цитат книга](Common.js.d/Edit%20tools%20data.d/Цитат%20книга) и [Цитат периодика](Common.js.d/Edit%20tools%20data.d/Цитат%20периодика).

2021-11-14 10:21 UTC, kerberizer commented on Common.js.d/Edit tools data.d/Цитат уеб
> +<nowiki>{{цитат уеб | уеб_адрес = >>|<< | заглавие = | дата = | достъп_дата = | фамилно_име = | първо_име = | автор_препратка = | издател = | архив_уеб_адрес = | архив_дата = | цитат = | език-скрит =
@petar-petrov-w Благодаря ти! Аз още се колебая за тия интервали. На мен ми харесва за прегледност както параметрите, така и стойностите им да са отделени с интервали от двете страни. Затова и за удобство преди бях слагал по два интервала, между които да се пейства. Но Румен вероятно е прав, че когато тези параметри не бъдат използвани, там просто остават два интервала след равното. Обаче за мястото за вмъкване може би все пак има смисъл да си стоят интервалите от двете страни. Така пействането е достатъчно, без да има нужда да се добавя и интервал за четимост. А параметърът уеб_адрес винаги ще бъде попълван. Не знам, наистина. Окей съм и с този вариант, и дори с вариант да махнем въобще интервалите, като се „компресира“ всичко.

2021-11-14 10:22 UTC, kerberizer commented on Common.js.d/Edit tools data.d/Цитат уеб
> +<nowiki>{{цитат уеб | уеб_адрес = >>|<< | заглавие = | дата = | достъп_дата = | фамилно_име = | първо_име = | автор_препратка = | издател = | архив_уеб_адрес = | архив_дата = | цитат = | език-скрит =
> Щом променяме форматирането тук, то нека го направим и за другите шаблони [Цитат книга](Common.js.d/Edit%20tools%20data.d/%D0%A6%D0%B8%D1%82%D0%B0%D1%82%20%D0%BA%D0%BD%D0%B8%D0%B3%D0%B0) и [Цитат периодика](Common.js.d/Edit%20tools%20data.d/%D0%A6%D0%B8%D1%82%D0%B0%D1%82%20%D0%BF%D0%B5%D1%80%D0%B8%D0%BE%D0%B4%D0%B8%D0%BA%D0%B0).

Това е разумно предложение, да.

2021-11-14 13:09 UTC, kerberizer commented
На [обсъждането в Уикипедия](
https://bg.wikipedia.org/wiki/%D0%A3%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F:%D0%97%D0%B0%D1%8F%D0%B2%D0%BA%D0%B8_%D0%BA%D1%8A%D0%BC_%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B8%D1%82%D0%B5#%7B%7B%D1%88%7C%D0%A6%D0%B8%D1%82%D0%B0%D1%82_%D1%83%D0%B5%D0%B1%7D%7D) междувременно има възражения, така че нека също видим какво ще се реши и там.

2021-11-14 15:19 UTC, petar-petrov-w commented on Common.js.d/Edit tools data.d/Цитат уеб
> +<nowiki>{{цитат уеб | уеб_адрес = >>|<< | заглавие = | дата = | достъп_дата = | фамилно_име = | първо_име = | автор_препратка = | издател = | архив_уеб_адрес = | архив_дата = | цитат = | език-скрит =
Нека продължим там тогава.  Аз започнах тук, защото в У нямаше коментари, а по-лесно се коментира код тука.  Но нека не раздрвояваме дискусията.

2021-11-14 17:38 UTC, kerberizer commented on Common.js.d/Edit tools data.d/Цитат уеб
> +<nowiki>{{цитат уеб | уеб_адрес = >>|<< | заглавие = | дата = | достъп_дата = | фамилно_име = | първо_име = | автор_препратка = | издател = | архив_уеб_адрес = | архив_дата = | цитат = | език-скрит =
съгласен!

2021-12-11 22:23 UTC, petar-petrov-w commented
Нищо не се реши.

2021-12-11 22:23 UTC, closed without merging